# Generated by Django 4.1.7 on 2023-04-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='User name')),
                ('last_name', models.CharField(max_length=30, verbose_name='User last name')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('email', models.CharField(max_length=30, verbose_name='User email')),
                ('password', models.CharField(max_length=30, verbose_name='User password')),
            ],
        ),
    ]
