# Generated by Django 4.1.7 on 2023-05-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0004_profile_bio_profile_jobs_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_imgae',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
