# Generated by Django 4.1.7 on 2023-05-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0006_alter_profile_bio_alter_profile_jobs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_imgae',
            new_name='profile_image',
        ),
    ]
