# Generated by Django 4.1.7 on 2023-05-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0008_rename_bio_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eduction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
