# Generated by Django 4.1.7 on 2023-05-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0009_profile_eduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='eduction',
            new_name='education',
        ),
    ]
