# Generated by Django 4.1.7 on 2023-05-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0012_alter_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('type_of_workplace', models.CharField(max_length=200, null=True)),
                ('vacancy_region', models.CharField(max_length=200, null=True)),
                ('type_of_employment', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
