# Generated by Django 4.1.7 on 2023-05-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0013_vacancies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancies',
        ),
    ]
