# Generated by Django 4.1.7 on 2023-05-22 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrationapp', '0014_delete_vacancies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('type_of_workplace', models.CharField(max_length=200, null=True)),
                ('vacancy_region', models.CharField(max_length=200, null=True)),
                ('type_of_employment', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacacncy_of_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
