# Generated by Django 4.1.7 on 2023-05-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0019_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sort_posts',
            field=models.CharField(choices=[('P', 'Popularity'), ('L', 'Latest')], default='L', max_length=1),
        ),
    ]
