# Generated by Django 4.1.7 on 2023-05-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0020_post_sort_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_posts', models.CharField(choices=[('P', 'Popularity'), ('L', 'Latest')], default='L', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='sort_posts',
        ),
    ]
