# Generated by Django 4.1.7 on 2023-05-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0021_orderedpost_remove_post_sort_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedPost',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
