# Generated by Django 4.1.7 on 2023-06-01 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrationapp', '0023_company_companyprofile_post_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
