# Generated by Django 4.1.7 on 2023-06-01 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0025_remove_company_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='company_image',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='user',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registrationapp.company'),
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='company',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ManyToManyField(related_name='vacancy_of_company', to='registrationapp.company'),
        ),
    ]
