# Generated by Django 4.1.7 on 2023-06-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0026_remove_companyprofile_follows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_companies', to='registrationapp.company'),
        ),
    ]
