# Generated by Django 4.1.7 on 2023-06-01 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrationapp', '0027_companyprofile_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
