# Generated by Django 4.1.7 on 2023-06-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0028_alter_companyprofile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='bio_vacancy',
            field=models.TextField(null=True),
        ),
    ]
