# Generated by Django 4.1.7 on 2023-06-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0030_remove_vacancy_company_vacancy_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
