# Generated by Django 4.1.7 on 2023-06-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0031_vacancy_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
