# Generated by Django 4.1.7 on 2023-06-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0032_vacancy_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comapany',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
