# Generated by Django 4.1.7 on 2023-06-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0033_company_comapany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='comapany',
            new_name='employee',
        ),
    ]
