# Generated by Django 4.1.7 on 2023-06-02 10:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0034_rename_comapany_company_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='bio_vacancy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
