# Generated by Django 4.1.7 on 2023-06-03 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrationapp', '0035_alter_vacancy_bio_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
