# Generated by Django 4.1.7 on 2023-06-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0036_vacancy_favourites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_event', models.CharField(blank=True, max_length=200, null=True)),
                ('event_href', models.CharField(blank=True, max_length=200, null=True)),
                ('event_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
