# Generated by Django 4.1.7 on 2023-06-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0037_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
