# Generated by Django 4.1.7 on 2023-06-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0039_rename_event_href_event_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_location',
            new_name='event_url',
        ),
    ]
