# Generated by Django 4.1.7 on 2023-06-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0040_rename_event_location_event_event_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='data_event',
            new_name='event_datatime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_data',
            new_name='event_type',
        ),
    ]
