# Generated by Django 4.1.7 on 2023-06-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0042_event_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_datatime',
            new_name='event_datetime',
        ),
    ]
