# Generated by Django 4.1.7 on 2023-03-07 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('job_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_created', models.DateField()),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('job_title', models.TextField()),
                ('job_description', models.TextField()),
                ('job_requirements', models.TextField()),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
        ),
    ]
